### ISSUE TITLE
Installation requirements

### ISSUE THREAD

**Issue by bkmgit** [sourceryinstitute/jupyter-CAF-kernel#4]
This is nice. Would be helpful if could use GCC and Gfortran 5. OpenCoarrays will also work with OpenMPI

**Comment by zbeekman** [comment]
Hi Benson,

Can you please clarify what the issue is? Do you just want documentation of what the installation requirements are?

You really need GCC/GFortran >= 6.1 for decent OpenCoarrays support.

FYI, there are docker images (that I may need to update) that have everything you need.

Let me know how I can help & make things clearer.

**Comment by ansh997** [comment]
Hi, I want to use coarray-fortran locally. For that I followed the steps given but it shows following issues:
jupyter-kernelspec install prebuild/jupyter-caf-kernel/Coarray-Fortran/
after this it shows error:
[Errno 13] Permission denied: '/usr/local/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?
but with sudo also it asks for repo even after adding repo and following first three steps.
Please Help!

**Comment by zbeekman** [comment]
Hi @ansh997,

Do you just want to use plain Coarray Fortran locally or do you want to use Coarray Fortran with Jupyter notebooks locally?

If you just want to use Coarray Fortran, without jupyter, please see https://github.com/sourceryinstitute/OpenCoarrays

In the meantime I will look into a solution that will allow a more flexible installation.

**Comment by zbeekman** [comment]
P.S. Pull requests implementing suggested improvements are always welcome 😉

**Comment by zbeekman** [comment]
I think you can pass `--user` to your pip install command. I hope you sorted the issue out. If not feel free to re-open this issue.
