### ISSUE TITLE
Installation without sudo?

### ISSUE THREAD

**Issue by mittenchops** [sourceryinstitute/jupyter-CAF-kernel#5]
This is an awesome project.  

I'm installing on Ubuntu and I go through...

    (myenv) $ git clone https://github.com/sourceryinstitute/jupyter-CAF-kernel
    (myenv) $ cd jupyter-CAF-kernel
    (myenv) $ pip install -e prebuild/jupyter-caf-kernel
    (myenv) $ jupyter-kernelspec install prebuild/jupyter-caf-kernel/Coarray-Fortran/
    [Errno 13] Permission denied: '/usr/local/share/jupyter'
     Perhaps you want to install with `sudo` or `--user`?
    # jupyter-notebook .

Is it possible to modify this so it doesn't require sudo?

**Comment by TerenceLiu98** [comment]
If you want to install CAF-kernel in root please use `sudo` to install.

**Comment by adcwilliams** [comment]
I installed it doing exactly what pip suggested, just adding the `--user` option with no arguments. I expected to also have to add it to `PYTHONPATH` but it seems to work find without doing that.

**Comment by zbeekman** [comment]
Yes, I think you can do `pip install --user -e prebuild/jupyter-caf-kernel`... let me know if that works for you.

If not, feel free to reopen this issue.
